SELECTED_FEATURES = [
    "SV L5 x",
"SV L5 y",
"SV L5 z",
"SV T8 x",
"SV T8 y",
"SV T8 z",
"SV Neck x",
"SV Neck y",
"SV Head z",
"SV Right Upper Arm x",
"SV Right Upper Arm y",
"SV Right Upper Arm z",
"SV Right Forearm x",
"SV Right Forearm y",
"SV Right Forearm z",
"SV Right Hand x",
"SV Right Hand z",
"SV Left Upper Arm x",
"SV Left Upper Arm y",
"SV Left Upper Arm z",
"SV Left Forearm x",
"SV Left Forearm y",
"SV Left Forearm z",
"SV Left Hand x",
"SV Left Hand y",
"SV Left Hand z",
"SV Right Upper Leg x",
"SV Right Upper Leg y",
"SV Right Upper Leg z",
"SV Right Lower Leg x",
"SV Right Lower Leg y",
"SV Right Lower Leg z",
"SV Right Foot x",
"SV Right Foot y",
"SV Right Foot z",
"SV Left Upper Leg x",
"SV Left Upper Leg y",
"SV Left Lower Leg x",
"SV Left Lower Leg y",
"SV Left Lower Leg z",
"SV Left Foot x",
"SV Left Foot y",
"SV Left Foot z",
"SA L5 x",
"SA L5 y",
"SA L5 z",
"SA T8 z",
"SA Head x",
"SA Head z",
"SA Right Shoulder x",
"SA Right Shoulder y",
"SA Right Shoulder z",
"SA Right Upper Arm x",
"SA Right Upper Arm y",
"SA Right Upper Arm z",
"SA Right Forearm x",
"SA Right Forearm y",
"SA Right Forearm z",
"SA Right Hand y",
"SA Left Shoulder x",
"SA Left Shoulder y",
"SA Left Shoulder z",
"SA Left Upper Arm x",
"SA Left Upper Arm y",
"SA Left Upper Arm z",
"SA Left Forearm x",
"SA Left Forearm z",
"SA Left Hand x",
"SA Left Hand y",
"SA Left Hand z",
"SA Right Upper Leg y",
"SA Right Upper Leg z",
"SA Right Lower Leg z",
"SA Right Foot x",
"SA Right Foot y",
"SA Right Foot z",
"SA Left Upper Leg x",
"SA Left Upper Leg z",
"SA Left Lower Leg x",
"SA Left Lower Leg y",
"SA Left Lower Leg z",
"SA Left Foot x",
"SA Left Foot y",
"SA Left Foot z",
]